name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [closed]
    
  workflow_dispatch: # This allows you to manually trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular App
        run: ng build
      
      - name: List Contents of dist Subdirectory
        run: |
          ls -la $GITHUB_WORKSPACE/dist/*

      - name: Setup connection
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Sync to Server
        run: |
          rsync -avz --delete $GITHUB_WORKSPACE/dist/* root@$SSH_HOST:/var/www/html/
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: SSH into Server and Restart Apache
        run: |
          ssh root@$SSH_HOST 'chmod -R 755 /var/www/html && systemctl restart apache2'
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          
      - name: Deployment Status
        run: |
          echo 'Deployment successful to Digital Ocean'
