name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [closed]
    
  workflow_dispatch: # This allows you to manually trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular App
        run: ng build

      - name: List Contents of Build Directory
        run: |
          ls -la $GITHUB_WORKSPACE/dist
      
      - name: List Contents of dist Subdirectory
        run: |
          ls -la $GITHUB_WORKSPACE/dist/*
           
      - name: Deploy
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
          rsync -avz --exclude '.env' --exclude 'vendor/' ./ root@$SSH_HOST:/var/www/html/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SSH_HOST }}

      - name: SSH into Server and Restart Apache
        run: |
          ssh root@$SSH_HOST 'chmod -R 755 /var/www/html && systemctl restart apache2'
        env:
          SERVER_IP: ${{ secrets.SSH_HOST }}
