name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [closed]
    
  workflow_dispatch: # This allows you to manually trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular App
        run: ng build
      
      - name: List Contents of dist Subdirectory
        run: |
          ls -la $GITHUB_WORKSPACE/dist/*
           
      - name: Deploy to DigitalOcean
        run: |
          # Clear the existing contents of the Apache document root
          sshpass -p ${{ secrets.SSH_PASS }} ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'sudo rm -rf /var/www/html/*'

          # Use rsync to synchronize the dist directory with the remote server
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" $GITHUB_WORKSPACE/dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/

          # Restart Apache (adjust for your server setup)
          sshpass -p ${{ secrets.SSH_PASS }} ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'sudo systemctl restart apache2'
